# Welcome to Serverless!
#

service: geoip

provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  stage: ${opt:stage, 'dev'}
#  iamManagedPolicies:
#    - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
#    - arn:aws:iam::#{AWS::AccountId}:policy/service-role/DAXtoDynamoDBPolicy
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dax:GetItem'
        - 'dax:BatchGetItem'
        - 'dax:Query'
        - 'dax:DefineAttributeList'
        - 'dax:DefineAttributeListId'
        - 'dax:DefineKeySchema'
        - 'dax:Endpoints'
      Resource:
          - arn:aws:dynamodb:us-west-2::#{AWS::AccountId}:cache/*
    - Effect: 'Allow'
      Action:
        - 'dynamodb:DescribeTable'
        - 'dynamodb:GetItem'
        - 'dynamodb:BatchGetItem'
        - 'dynamodb:Query'
      Resource:
        - arn:aws:dynamodb:us-west-2:#{AWS::AccountId}:table/geoip_city*
  tracing:
    apiGateway: true
    lambda: true

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
#  - serverless-iam-roles-per-function

functions:
  lookup:
    handler: lookup.find
    events:
      - http:
          path: ip/{ip}
          method: get
      - http:
          path: ip
          method: get
  lookup_dax:
    handler: lookup_dax.find
    events:
      - http:
          path: ip_dax/{ip}
          method: get
      - http:
          path: ip_dax
          method: get
    vpc:
      securityGroupIds:
        - sg-1ea8316c
      subnetIds:
        - subnet-addf82d4

resources:
  Resources:
    geoipCityLocations:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: geoip_city_locations_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: geoname_id
            AttributeType: S
        KeySchema:
          - AttributeName: geoname_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1000
    geoipCityNlocksIp4:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: geoip_city_blocks_ip4_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: network
            AttributeType: S
        KeySchema:
          - AttributeName: network
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1000

